### ISSUE TITLE
Feature Request: choose between 2axis and 4axis joystick in the Options menu

### ISSUE THREAD

**Issue by Gagert** [libretro/dosbox-svn#11]
In the game Tyrian2k, you can have one player controlling the ship using keyboard, while the other player uses either the mouse or joystick as their controlling device.

In this libretro core you can map all the keyboard keys to an actual gamepad via the Controllers section in RetroArch, thereby making it possible to use two physical gamepads in the 2 player mode. However, by configuring this libretro core with only the settings in the Options menu, there's not an option to switch between 2axis or 4axis joystick (like I used to do with the DOSBox config files before). 

4axis applies to a single controller, giving you all the four directional buttons plus 4 action buttons. The 2axis mode (that seems to be default here) originally supports two controllers at once, both with directional buttons but with only 2 action buttons each.

Tyrian2k utilizes the 4axis controller functionality by giving all 4 action buttons a purpose, thereby limiting player 2's action if 2axis joysticks are selected by dos/dosbox itself.

**Edit:** I tried launching Tyrian2k via a *.conf file where I added both Gravis Ultrasound (which worked) and switched to 4axis by typing joysticktype=4axis under [joystick], but still I only got the option to map Button 1 & 2 under Joystick/Gamepad under the libretro/RetroArch keymapper in this libretro core.

It would be nice to have a single line in the Options menu to switch between 2axis and 4axis joystick for convenience.

**Edit 2:** I checked the libretro_mapper.cpp file found in the libretro folder of the dosbox-svn libretro branch; to my surprise it seems like the mapper already are configured for both 2axis- and 4axis gamepads. I then started Tyrian2k from this core and the mapper there, where I have User 1 Device as Keyboard & Mouse and User 2 Device as Joystick.

I tried switching a bit around in the Controls settings in RetroArch, by changing User 1 Device to Joystick and User 2 Device to Keyboard & Mouse in the dosbox svn core. Suddenly I had full 4axis support for the User 1 Device, with all the 4 action buttons.

However, I would prefer the User 1 Device to still be Keyboard & Mouse and User 2 Device to be Joystick, while still giving the secondary controller 4axis support (seems like Tyrian2k defaults player 1 to Keyboard). 

With my very limited programming knowledge (almost non-existent), and not being able to compile dosbox svn with msys2 even using the guide in the provided readme-file (I'm able to compile many of the libretro-super-master cores using msys2 with the ./libretro-build.sh command), I'm a bit stuck as of now.

**Comment by realnc** [comment]
The input mapper in the core is kinda borked. Will see if I can fix it.

**Comment by realnc** [comment]
It's... complicated. Not sure I can make it work. The problem is that a 4axis gamepad is actually two gamepads hacked into one. So there really isn't any notion of port1 vs port2. It uses both ports to expand the amount of buttons.

However, I just tried T2K and it seems it has configuration options for which player is using the gamepad. Doesn't that work for you?

**Comment by Gagert** [comment]
I see, I didn't know the technical details of the difference between 2axis and 4axis gamepads.

Could it be feasible to make the dos-gamepads skip "User 1 Device type" in this core via a toggle-able setting in Options (making only "Keyboard + Mouse" available in the Controls menu for Player 1 in RetroArch) and thereby make "User 2 Device type" the first device to have the dos-gamepads available? In that way, since RA maps keyboard commands to any gamepads and so on, the 4axis controller could in theory without any issues work on the "User 2 Device type", since the gamepads with this setting just skips "User 1 Device type" entirely?

It might not be worth to do all the effort for such a task, I can understand that. Tyrian2k indeed works with Player 1 using a 4axis gamepad, but personally I prefer it if Player 1 has control over the Esc-button, Pause button and so on, and only the player "wielding" the "Keyboard + Mouse" has that power. That works the best on a HTPC-setup with gamepads in the couch in front of the TV. Also, it seems like the gamepad can't navigate the menus in Tyrian2k during my quick and limited testing.

**Comment by fr500** [comment]
If you set only one player to gamepad it's 4axis
If you set p1 and p2 it's 2xis

**Comment by realnc** [comment]
> If you set only one player to gamepad it's 4axis
> If you set p1 and p2 it's 2xis

Unfortunately, that is not true. I only need one user in RA. So it's set to 1. But if you do that, and configure the core option to gamepad or joystick, you only get 2axis and the core thinks there's two gamepads connected.

**Comment by fr500** [comment]
Hmmm then that's broken, it was supposed the way I mentioned, I'll fix it

**Comment by realnc** [comment]
I'm not sure it's fixable on the core. It should probably be changed in RA. `retro_set_controller_port_device()` will get called for 5 ports, even if I told RA to only use 1 user. For ports >0, RA will tell `retro_set_controller_port_device()` that a `RETRO_DEVICE_JOYPAD` is connected there, which is a lie, but that's what the spec says.

As a result, `MAPPER_Init()` can never activate 4axis, since RA lied and told us there's 2 gamepads connected...

I think this part of the spec should be changed. Missing ports should not be reported a JOYPAD. They either should be reported as NONE, or not reported at all.

**Comment by fr500** [comment]
works fine here

![image](https://user-images.githubusercontent.com/1721040/68678286-b1074e00-052b-11ea-9c1b-310feee7b50c.png)
![image](https://user-images.githubusercontent.com/1721040/68678274-ab116d00-052b-11ea-8cb7-66602b2362b8.png)


![image](https://user-images.githubusercontent.com/1721040/68678307-b9f81f80-052b-11ea-8074-08ed2374edf6.png)
![image](https://user-images.githubusercontent.com/1721040/68678318-bd8ba680-052b-11ea-8123-8668da9a003c.png)


![image](https://user-images.githubusercontent.com/1721040/68678346-c7150e80-052b-11ea-8d33-add091f12c73.png)
![image](https://user-images.githubusercontent.com/1721040/68678362-cf6d4980-052b-11ea-95f3-05e27e70cf49.png)

**Comment by realnc** [comment]
You don't seem to have "Max Users" set to 1 in Settings/Input.

**Comment by fr500** [comment]
Yeah I don't that whole thing is badly implemented in the frontend.

**Comment by realnc** [comment]
Well, that's what I said :-P The core has no way to tell what ports are actually connected since RA just lies about it. This is my setup, which is what a sane person would expect to be the proper setup, but it doesn't work and only gives 2axis:

![image](https://user-images.githubusercontent.com/1665903/68678726-27757180-0567-11ea-9101-b929f10d689c.png)

**Comment by realnc** [comment]
@Gagert 
You might want to try the new core called "DOSBox-core". I added 4axis support for the second port. If you set port 1 to "keyboard and mouse", port 2 will automatically become 4axis_2.

**Comment by Gagert** [comment]
@realnc 
Thanks for the response. I have now installed DOSBox-core in RetroArch, and it actually works flawlessly now!!!

Finally me and a buddy can play Tyrian2k together in my couch using gamepads (that being said, after a certain epidemic is no longer a threat & I can have visitors again).
