### ISSUE TITLE
Screen Tearing in Mario & Luigi fan-game & in 70fps titles in general

### ISSUE THREAD

**Issue by Gagert** [libretro/dosbox-svn#19]
There is this fan-game known as Mario & Luigi for MS-DOS (plays a lot like Super Mario Bros 3) that I'm having a hard time getting to run in the DOSBox SVN libretro core without getting any kind of screen tearing. By pressing F3 in-game I could in RetroArch see the actual framerate, which seems to be 70fps.

I'm currently using a 1080p LCD-TV which runs at 60hz max, so by looking at those specs it seems obvious that screen tearing will occur some way or other on my setup in a 70fps game.

However, somehow I didn't encounter any screen tearing at all in DOSBox ECE while running the very same game. In DOSBox ECE I'm using surface as the output video system (surfacepp to be exact because of pixel-perfect output mode).

The same thing happens in the old Home Alone 1 game (which also seem to run in 70fps) in this libretro core. I tried to change the emulated machine settings a couple of times to see if that helps, and also switching between other settings in the Options menu, but I still haven't found a way to get rid of this screen tearing for 70fps games in this libretro core.

**Comment by realnc** [comment]
Set the "Video: Enable refresh rate switching" option to "false". This should prevent RA from disabling vsync when a DOS game uses a 70Hz VGA mode. This setting is really only useful if you have a 70Hz or a VRR (g-sync/freesync) display.

(In the current core version,you need to restart the core for this to take effect when you change it from "true" to "false".)

**Comment by Gagert** [comment]
Thanks; that worked!

(I previously tried to change the refresh rate switching without restarting RA itself, so that's why that options didn't do anything for me previously).

**Comment by ToniBC** [comment]
This option still exists ?? I can't find it anywhere, there is only one similar that is by default OFF, which is G-Sync.

There is some way of not having Tearing as the partner comments or it is not possible.

Thank you.

**Comment by realnc** [comment]
@ToniBC The option is now called "Core: Timing Mode". It's a core option, not a RetroArch option.

**Comment by realnc** [comment]
Also, prefer DOSBox-core if it's available on your system, not DOSBox-SVN, as that's the legacy core. DOSBox-core is the modern one.
