### ISSUE TITLE
imgmount fails with "can't create drive from file"

### ISSUE THREAD

**Issue by evbo** [libretro/dosbox-svn#41]
I have a windows 98se image running in [dosbox-svn-daum](http://www.ykhwong.x-y.net/) on Windows 7 host (not in retroarch) as my prototype and I am now wondering if this same image could be mounted through retroarch using this dosbox-svn core?

When I try through retroarch using this core I run into the exact same issue as posted here: https://www.vogons.org/viewtopic.php?t=33667

However, if I try to work around it, I can get `imgmount` to succeed:

`imgmount 2 C:\win98.img -size 512,63,16,4063 -t hdd -fs none`

However, then if I run `boot -L C` I get:

> Booting from drive C...
> Disk I/O Error
> Replace the disk and press any key

dosbox-svn-daum on the other hand boots fine with my original command below. Any idea how to make this work for dosbox-svn core in retroarch?:
`imgmount c C:\win98.img -size 512,63,16,4063 -t hdd -fs fat`

**Comment by evbo** [comment]
I think I know why this happens. It appears to only be an issue mounting hdd images greater than 512 MB.

So now my question, if this is the case, is to figure out how to mount 2 GB for a win9x game.

**Comment by realnc** [comment]
If it doesn't work in stand-alone dosbox-svn then it also won't work in this core.

**Comment by evbo** [comment]
thank you, the issue was I was creating these image files not using dosbox. And the difference in number of heads and cylinders was causing an issue for windows apparently.
