### ISSUE TITLE
Mouse movement area incorrect when Game Focus is off

### ISSUE THREAD

**Issue by jstolarek** [libretro/dosbox-svn#58]
In games that use mouse, the initial mouse movement area is restricted. For example, consider this screenshot from Warcraft 2 menu:

![war2_2](https://user-images.githubusercontent.com/1597921/83647711-1c3e6d80-a5ad-11ea-834b-6c749d85eeae.jpg)

Notice how the mouse cursor is placed on "Show Credits" button - at this point it is impossible to move the cursor lower, which makes the "Exit Program" button unreachable. After moving the cursor around it unlocks at some point and can move on the whole area of the screen. Same happens to other games that use the mouse (Syndicate, Settlers 2). If I enable game focus (the key can be bound in Input > Hotkey Binds > Game Focus Toggle, in my case this is a Scroll Lock) the problem instantly disappears. It is instructive to enable and then immediately disable Game Focus mode - then you can see both the DOS game cursor and the OS cursor moving at the same time. It is then obvious that the restriction in the game cursor movement comes from the OS cursor reaching the lower border of the screen and not being able to move past it. This is some sort of scaling error. Doesn't happen with standalone DOSBox. Tested on Linux.

**Comment by realnc** [comment]
This is a RetroArch thing, I'm afraid. The core does not know anything about focus mode. All it does is forward the mouse movements reported by RetroArch to DOSBox.

This affects all cores that support mouse input. P-UAE for example when running a point&click adventure game will exhibit the same behavior. So you can file an issue on the RA repo:

https://github.com/libretro/RetroArch

**Comment by jstolarek** [comment]
Will do, thanks. (I'm doing a marathon of reporting RA bugs today.)
