### ISSUE TITLE
Screen flooded with text in Prince of Persia

### ISSUE THREAD

**Issue by jstolarek** [libretro/dosbox-svn#59]
Running Prince of Persia in DOSBox-SVN results in screen being flooded with text "JoyX:  64 JoyY:  64 Btn:   0":

![pop](https://user-images.githubusercontent.com/1597921/83653725-097b6700-a5b4-11ea-981c-225e297782c1.jpg)

This makes the game unplayable. Doesn't happen with standalone DOSBox. The core is running with default options and the input is set to Keyboard + Mouse.

**Comment by realnc** [comment]
> Doesn't happen with standalone DOSBox.

Hm. Are you sure? https://www.vogons.org/viewtopic.php?t=33618

**Comment by jstolarek** [comment]
>  Are you sure?

It doesn't happen with the DOSBox that I have, which is v0.74-2. I have no idea what exodos is. I'm on Debian Buster and using a package from official repo. I just tested on dosbox-staging v0.75 and interestingly the problem happens there as well. But the thread you linked to is right - it only happens with version 1.4 of the game. Version 1.3 works as expected.

> it's always useful to test the more modern dosbox core (listed as "DOSBox-core" in the RA updater)

Wait, I thought that DOSBox-SVN is more modern?

Closing, since this does not seem to be a problem of the core itself.

**Comment by realnc** [comment]
> Wait, I thought that DOSBox-SVN is more modern?

Nope. It does keep in sync with upstream dosbox (thus the "svn" in the name), but new features are added to DOSBox-core. DOSBox-svn is kind of a "legacy" or "compatibility" core, while DOSBox-core is has been split from it and has received a rewrite of many parts of the code, and additions of features that don't exist in upstream dosbox.
