### ISSUE TITLE
Inconsistent .conf file naming when created and read (DOSBox-SVN CE)

### ISSUE THREAD

**Issue by spinningacorn** [libretro/dosbox-svn#62]
This is probably trivial, but it got me splitting hairs on why the file wasn't being recognized: the command "config -wcd" writes the .conf file in ./saves/ as "DOSBox-SVN-CE.conf", however it's only read after being renamed "DOSBox-SVN CE.conf" (second dash replaced with a space).

**Comment by realnc** [comment]
The CE core is dead. Use [DOSBox-core](https://github.com/realnc/dosbox-core#dosbox-core) instead.
