### ISSUE TITLE
MT-32 / Munt 

### ISSUE THREAD

**Issue by vol-2** [libretro/dosbox-svn#63]
I can't get MT-32 music to work. If someone could please help me I would be grateful.

Setup is Retroarch running in Raspberry Pi OS. I have Munt installed and it works as expected in dosbox outside of RA, so I know that's good.

From bootup, doing an "aconnect -o" in the console gives me client 14  and client 128. 14 is the "Midi Through Port 0" device (at 14:0), and 128 is the MT-32 (at 128:0)

When I launch RA, I see in Midi devices only client 14, but it doesn't even enumerate the client, it only shows the device, in this case "Midi Through Port 0".

I see midi settings in dosbox-svn.conf, dosbox-svn.opt, and in retroarch.cfg. Perhaps I'm missing something, but that's all I can find. I have tried many different combos of these and no luck.
I'm using the Dark Forces sound setup menu to test because it's easy to get into, and it features a music-digital sound side-by-side menu that I can easily idiot-check that I'm still getting SB sound. 

Right now, I have things like this:
retroarch.cfg:
midi_driver = "alsa"    
midi_input = "128:0" ###also tried "MT-32", "Midi Through Port 0", "Off"
midi_output = "128:0" ###also tried "MT-32", "Midi Through Port 0", "Off"

dosbox-svn.opt:
dosbox_svn_midi = "true"###also tried with (dosbox_svn_use_options = "false")

dosbox-svn.conf:
mpu401     = intelligent
mididevice = alsa ###also tried "MT-32", "default" "128:0"
midiconfig = 128:0 ###also tried "MT-32", "default", "alsa"

One more thing, when I open RA (or possibly when I open Dosbox SVN, I see an extra midi entry when I query the console via SSH. It creates a "client 129" input.

That's about where I'm at. Can anyone help me get MT-32 music going in this?

Thanks,

**Comment by realnc** [comment]
Use [DOSBox-core](https://github.com/realnc/dosbox-core#dosbox-core) instead, which has built-in support for MT-32 (Munt), as well as external MIDI support to select the correct MIDI ports in the core options if you want to use the external, stand-alone version of  Munt.

**Comment by vol-2** [comment]
> Use [DOSBox-core](https://github.com/realnc/dosbox-core#dosbox-core) instead, which has built-in support for MT-32 (Munt), as well as external MIDI support to select the correct MIDI ports in the core options if you want to use the external, stand-alone version of Munt.

I'm not picky about where my MT-32 support comes from and I like some of the SVN features. Is there a way to enable _any_
 MT32 music in SVN _at all_, or is it impossible?

Thanks,

**Comment by realnc** [comment]
> and I like some of the SVN features

dosbox-core has all SVN features, plus extra stuff. dosbox-svn is the legacy core for old systems where dosbox-core doesn't run.

**Comment by vol-2** [comment]
Gotcha. I was under the impression that the reverse was true. In most other arenas I usually see SVN as the latest and greatest.

I tried out Core and it is indeed running MT-32 stuff. I think I'm using the non-Munt MT32 though. I can't figure out how to set it up so that it passes through to the Munt client as it appears that RA and Core both only see the Client 14 "Midi Through Port 0"

Is this just a limitation of my setup, or am I just pooching the settings some how?

Thanks

**Comment by realnc** [comment]
The Munt client is using ALSA, so in the core options select "ALSA" in the "Sound: MIDI driver" option. Make sure Munt is already running though before you start the core. Munt then should show up as one of the ports in the "Sound: ALSA MIDI port" option. The core will remember the port by name, so even if the port number of the Munt client changes in the future, it will find the port since it's still called "Munt MT-32":

![](https://i.imgur.com/eouOuWm.png)

**Comment by realnc** [comment]
If, on the other hand, you want to use the built-in Munt that comes with the core, then set the "MIDI driver" core option to "MT-32 emulator". Make sure you copy the MT-32 ROMs (`CM32L_CONTROL.ROM`, `CM32L_PCM.ROM`, `MT32_CONTROL.ROM` and `MT32_PCM.ROM`) to the RA system directory. Then you don't need to run an external Munt client anymore.

**Comment by vol-2** [comment]
Ok. I wasn't seeing the 128:0 option in my menu. It only had 14:0 available. I'll try it again, but I'm pretty sure. Thanks for the more detailed info.

I've got the second option running though.

Thanks  again :)
