### ISSUE TITLE
Nintendo Switch Internal FPS problem

### ISSUE THREAD

**Issue by evillurker** [libretro/dosbox-svn#70]
Hello, thank you for your kind work, the core works great on the PS Vita.
I just got my switch set up with retroarch and I moved all my vita contents into the switch.

There are 3 timing modes: Internal (fixed 60), internal (variable) and external.

There seems to be a problem with either the internal/external fps setting, or the internal, on the nintendo switch core specifically.

Setting internal fps (fixed 60) will cause frameskip problems so I tend to avoid it in certain games like Another World or Simon the Sorcerer II (Does not happen in flashback or sam & max for example)

But when I go for external / internal (variable) I get a weird slowdown which causes sound crackling issues. This does not happen on ths ps vita is something must be wrong on the switch core.

Tested on full ram access of course, and on the latest nightly build + latest stable

If you could fix that I would be very pleased.

Thanks for all your hard work!

**Comment by realnc** [comment]
It seems RetroArch does not disable vsync on Switch. For 70Hz DOS games, when running on a 60Hz display, vsync needs to be disabled when not using the fixed 60Hz internal mode.

There's nothing that can be done here from the core's side. It's a RetroArch issue.

**Comment by evillurker** [comment]
Hello. I managed to fix the issue thanks to m4xw . He told me to turn on hard gpu sync and change audio latency.
Audio letancy changed from 64 to 32 and no more audio crackling on internal/external mode
