### ISSUE TITLE
Core timing mode?

### ISSUE THREAD

**Issue by reignerdeustcher** [libretro/dosbox-svn#74]
It says that internal introduces lag and judder then what is the point of using it?

**Comment by realnc** [comment]
It's for running 70Hz DOS games (there's many of them) on 60Hz displays without tearing. It's not only 70Hz games though. Sometimes, games use weird VGA modes that use oddball refresh rates. Normally the best way to run dosbox is on a VRR display (g-sync/freesync) at the highest refresh rate your display supports. But if you can't do that, then internal mode can be useful to get rid of tearing.

**Comment by reignerdeustcher** [comment]
> 
> 
> It's for running 70Hz DOS games (there's many of them) on 60Hz displays without tearing. It's not only 70Hz games though. Sometimes, games use weird VGA modes that use oddball refresh rates. Normally the best way to run dosbox is on a VRR display (g-sync/freesync) at the highest refresh rate your display supports. But if you can't do that, then internal mode can be useful to get rid of tearing.

but how can i disable this? it makes all the games more sluggish than in normal dosbox using the same settings...

and i have a 75 hz monitor with freesync active

**Comment by realnc** [comment]
> but how can i disable this? it makes all the games more sluggish than in normal dosbox using the same settings...
> 
> and i have a 75 hz monitor with freesync active

Don't use internal mode then. Use external mode and configure RetroArch to use VRR (https://www.libretro.com/index.php/category/g-sync/)
