### ISSUE TITLE
There's not an accurate core timing for FPS into Jill of the jungle game, Retroarch

### ISSUE THREAD

**Issue by nad53** [libretro/dosbox-svn#78]
Hello there. I found that there's a game known as Jill of the jungle and anytime I play this game, the core doesn't seem to set an accurate timing for frames per second in order to play this game...

In standalone this game works flawlessly, but within RetroArch - core options, it's set to Internal (fixed 60fps) by default. Problem here is that apparently Jill of the jungle runs in around 63fps. I just saw somewhere else that another guy had a problem with the fps and other DOS game ran in 63 fps as well, but didn't relate to this issue in retroarch.

The problem with running locked 60fps is that overall if you're running with character as long as you start a new game then you can notice some skipped frames which are not caused by the Retroarch feature -runahead latency. 

Anyway, if I set to internal (variable) or external (variable) the game runs in the proper FPS as it should, but sound gets massive crackling and slowdowns overall. I haven't encountered other games that may run in 63fps but still, I'd appreciate if this could be addressed to fix into RetroArch dosbox svn-core.

Thanks for any reply or info.

**Comment by realnc** [comment]
This is a 70FPS game, not 63.

But in general, for games that run at higher than 60FPS and you don't have a high refresh rate monitor, you need to make sure that vsync is not forced somewhere. The vsync option in your GPU driver control panel needs to be set to "application controlled".

As a side note, dosbox-svn is not actively maintained anymore. Use either [dosbox-core](https://github.com/realnc/dosbox-core#readme) or [dosbox-pure](https://github.com/schellingb/dosbox-pure#readme).

**Comment by nad53** [comment]
> 
> 
> This is a 70FPS game, not 63.
> 
> But in general, for games that run at higher than 60FPS and you don't have a high refresh rate monitor, you need to make sure that vsync is not forced somewhere. The vsync option in your GPU driver control panel needs to be set to "application controlled".
> 
> As a side note, dosbox-svn is not actively maintained anymore. Use either [dosbox-core](https://github.com/realnc/dosbox-core#readme) or [dosbox-pure](https://github.com/schellingb/dosbox-pure#readme).

Thank you so much for the kind help

**Comment by realnc** [comment]
You're welcome. I guess I can close this then?
