### ISSUE TITLE
MUNT Windows driver not recognized nor found by emulator

### ISSUE THREAD

**Issue by biffrapper** [libretro/dosbox-svn#84]
For some reason DOSBOX-SVN does not seem to recognize MUNT in this libretro version of dosbox.  I have tried the older 32 bit driver and the newer 64 bit drivers, both windows installations, and when I do a mixer /listmidi from within dosbox, they never show up.  Additionally, if I try and use something such as Coolsoft midi mapper to switch my default midi device to MUNT, I still cannot get the core to output to the virtual device.

In non-SVN builds of dosbox, when I do a "mixer /listmidi" input, the virtual MUNT midi device shows up in the list of midi options, and then I can do a midiconfig "number" to select the device for all programs executed within the core to use.  This works perfectly in non-libretro versions of DOSBox.

GIven that MT-32 hardware is aging, and how accurate the MUNT emulator is of the device, support for this is essential.

**Comment by realnc** [comment]
This core does not support external MIDI. You can use DOSBox-core for that: 

https://github.com/realnc/dosbox-core#dosbox-core

**Comment by biffrapper** [comment]
Thank you!  DOSBox-core has solved my problem.  Appreciate the speedy, helpful reply.  :)
